name: flutter_base_module_1
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # networking
  retrofit: any
  logger: any
  json_serializable: ^6.1.3
  json_annotation: ^4.4.0

  # di
  injectable: any
  get_it: any

  # bloc
  flutter_bloc: ^8.0.0

  # local db
  floor: ^1.2.0

  # core
  flutter_base_config:
    path: ../flutter_base_config
  flutter_base_core_module_1:
    path: ../flutter_base_core_module_1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # generator
  retrofit_generator: any
  build_runner: any
  injectable_generator: any
  floor_generator: ^1.2.0
  copy_with_extension_gen: ^2.0.3

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.example.flutter_base_module_1.flutter_base_module_1
    iosBundleIdentifier: com.example.flutterbasemodule1.flutterBaseModule1
