name: flutter_base_config
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # networking
  retrofit: any
  logger: any
  json_serializable: ^6.1.3
  json_annotation: ^4.4.0

  # di
  injectable: any
  get_it: any

  # bloc
  flutter_bloc: ^8.0.0

  # local db
  floor: ^1.2.0

  # firebase
  firebase_core: ^1.10.6
  firebase_analytics: ^9.0.4
  firebase_messaging: ^11.2.4
  cloud_firestore: ^3.1.5

  # other
  flutter_local_notifications: ^9.1.5
  rxdart: ^0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # generator
  retrofit_generator: any
  build_runner: any
  injectable_generator: any
  floor_generator: ^1.2.0
  copy_with_extension_gen: ^2.0.3


flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.flutter_base_config
    iosBundleIdentifier: com.example.flutterBaseConfig
