settings:
  class_name: BuildConfiguration

environments:
  - dev
  - prod

natrium_variables:
  BundleIDRoot:
    dev,prod: com.sekiroflutter

  BundleID:
    dev: .dev
    prod: ""

plists:
  "./Runner/Info.plist":
    CFBundleDisplayName:
      dev: Weather Dev
      prod: Weather

    CFBundleName:
      dev,prod: flutter_base

    CFBundleIdentifier: "#{BundleIDRoot}#{BundleID}"

appicon:
  original: Runner/Icon-App-1024x1024@1x.png
  appiconset: Runner/Assets.xcassets/AppIcon.appiconset
  idioms:
    - ipad
    - iphone
  ribbon:
    dev: "dev"
    prod: ""

files:
  Runner/GoogleService-Info.plist:
    dev: Runner/GoogleService-Info-dev.plist
    prod: Runner/GoogleService-Info-prod.plist
#
#  Runner/AppDelegate.swift:
#    DEV: Runner/AppDelegate-DEV.swift
#    Production: Runner/AppDelegate-PROD.swift
