name: flutter_base_core_module_1
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # networking
  retrofit: any
  logger: any
  json_serializable: ^6.1.3
  json_annotation: ^4.4.0

  # di
  injectable: any
  get_it: any

  # bloc
  flutter_bloc: ^8.0.0

  # local db
  floor: ^1.2.0

  # other
  rxdart: ^0.27.3

  # other module
  flutter_base_config:
    path: ../flutter_base_config
  intl: ^0.17.0

  # others
  rive: ^0.7.33
  shared_preferences: ^2.0.11
  pull_to_refresh: ^2.0.0
  copy_with_extension: ^2.0.2
  flutter_alice: ^1.0.2
  overlay_support: ^1.2.1
  sorting_native: ^0.0.1
  walletconnect_dart: ^0.0.11
  walletconnect_secure_storage: ^1.0.0
  flutter_secure_storage: ^5.0.2
  qr_flutter: ^4.0.0
  flutter_inapp_purchase: ^5.3.1
#  in_app_purchase: ^3.0.6
#  sorting_native:
#    git:
#      url: https://github.com/tungtd95/sorting-native.git
#      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # generator
  retrofit_generator: any
  build_runner: any
  injectable_generator: any
  floor_generator: ^1.2.0
  copy_with_extension_gen: ^2.0.3

  test: any
  mockito: ^5.0.17
  bloc_test: any
  intl_utils: ^2.6.0
  flutter_flavorizr:
    git:
      url: https://github.com/tungtd95/flutter_flavorizr.git
      ref: v2.2.0

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.example.flutter_base_core_module_1
    iosBundleIdentifier: com.example.flutterBaseCoreModule1
